In [1]:
# Import pandas to read the CSV file as a table.
import pandas as pd

# Read the raw survey file from the project's raw folder.
raw_data = pd.read_csv("../raw/survey_responses.csv")

# Keep a short reference to the loaded DataFrame for later SQL queries.
df = raw_data

# Display the loaded data to confirm that the file was loaded correctly.
raw_data

,response_time,python_level,background,class_direction,python_topics,architecture_topics,learning_style,expectations_rating,pace,difficulty,theory_practice_balance
0,9/30/2026 17:38:50,I can write basic scripts,Career switcher,Move forward – architecture-level design with ...,"pandas / data manipulation, PySpark, Working w...","Batch vs. streaming pipelines, Data lake / war...",An end-to-end project we build together,4,Just right,Just right,Well balanced
1,9/30/2026 17:39:29,Comfortable with libraries like pandas,Career switcher,A mix – short basics refreshers alongside arch...,"PySpark, Working with SQL from Python, APIs an...","ETL vs. ELT patterns, Transformation tools (e....","An end-to-end project we build together, Real-...",3,Just right,Too hard,Too much theory
2,9/30/2026 18:04:44,Beginner – still learning the syntax,Career switcher,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","ETL vs. ELT patterns, Orchestration (e.g. Airf...","An end-to-end project we build together, Real-...",3,Just right,Too hard,Well balanced
3,9/30/2026 18:11:39,I can write basic scripts,Student,A mix – short basics refreshers alongside arch...,"PySpark, Working with SQL from Python, APIs an...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
4,9/30/2026 19:25:51,I can write basic scripts,Front End Developer,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
5,9/30/2026 19:40:52,I can write basic scripts,Full Stack Web Developer,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
6,9/30/2026 19:55:48,I can write basic scripts,Career switcher,Move forward – architecture-level design with ...,"pandas / data manipulation, PySpark, Working w...","Data lake / warehouse / lakehouse design, ETL ...","An end-to-end project we build together, Real-...",5,Just right,Just right,Too much theory
7,9/30/2026 20:08:19,Beginner – still learning the syntax,NaN,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...",I don't have much information about it,"Live coding sessions, An end-to-end project we...",3,Just right,Just right,Well balanced
8,9/30/2026 21:37:16,Beginner – still learning the syntax,Data / BI analyst,Strengthen basics – Python and core libraries ...,"Core Python (functions, OOP, error handling)",Batch vs. streaming pipelines,Live coding sessions,1,Just right,Just right,Well balanced
9,9/30/2026 21:54:53,I can write basic scripts,Student,Move forward – architecture-level design with ...,"PySpark, APIs and data ingestion (requests, JSON)","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
10,9/30/2026 22:33:18,Comfortable with libraries like pandas,Student and switch the career,Move forward – architecture-level design with ...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","Live coding sessions, Real-world case studies,...",3,Just right,Just right,Too much theory
11,9/30/2026 22:35:01,I can write basic scripts,Data / BI analyst,Strengthen basics – Python and core libraries ...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","Live coding sessions, Real-world case studies,...",3,Just right,Just right,"Too much hands-on, not enough explanation"
12,9/30/2026 23:17:35,Comfortable with libraries like pandas,Data / BI analyst,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, Working w...","ETL vs. ELT patterns, Orchestration (e.g. Airf...","Live coding sessions, Theory and concepts first",4,Just right,Just right,Too much theory
13,9/30/2026 23:19:59,Comfortable with libraries like pandas,Data / BI analyst,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, APIs and ...","Batch vs. streaming pipelines, Transformation ...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
14,9/30/2026 23:38:10,Beginner – still learning the syntax,Career switcher,A mix – short basics refreshers alongside arch...,Working with SQL from Python,"Data lake / warehouse / lakehouse design, Data...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
15,9/30/2026 23:52:23,I can write basic scripts,Student,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","An end-to-end project we build together, Real-...",4,Just right,Too hard,Well balanced
16,10/1/2026 0:35:57,Comfortable with libraries like pandas,Student,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, APIs and ...","Batch vs. streaming pipelines, Data lake / war...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
17,10/1/2026 0:40:00,I can write basic scripts,Student,Move forward – architecture-level design with ...,"PySpark, Working with SQL from Python, APIs an...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",3,Too slow,Just right,Too much theory
18,10/1/2026 6:21:23,Comfortable with libraries like pandas,Student,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Cloud data platforms (AWS / GCP / Azure), Data...","Live coding sessions, Theory and concepts firs...",4,Just right,Just right,Well balanced

### Cell 1 explanation

This cell begins the ETL process by importing pandas, a library for working with tabular data. It reads ../raw/survey_responses.csv into a DataFrame named raw_data. The relative path starts in the notebook folder, moves up to the project root, and then enters the raw folder.

df = raw_data gives the same table a shorter name for later SQL queries. The final line displays the loaded table so we can confirm that the file was read correctly. The source contains 19 survey responses and columns for Python level, background, class direction, selected topics, learning style, expectations, pace, difficulty, and theory/practice balance.

In [2]:
import pandas as pd
from pandasql import sqldf

# Load the CSV first
raw_data = pd.read_csv("../raw/survey_responses.csv")

# Run SQL on the loaded DataFrame
query = """
SELECT
    ROW_NUMBER() OVER (ORDER BY response_time) AS survey_key,
    *
FROM raw_data
"""

df = sqldf(query, {"raw_data": raw_data})
df

,survey_key,response_time,python_level,background,class_direction,python_topics,architecture_topics,learning_style,expectations_rating,pace,difficulty,theory_practice_balance
0,1,10/1/2026 0:35:57,Comfortable with libraries like pandas,Student,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, APIs and ...","Batch vs. streaming pipelines, Data lake / war...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
1,2,10/1/2026 0:40:00,I can write basic scripts,Student,Move forward – architecture-level design with ...,"PySpark, Working with SQL from Python, APIs an...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",3,Too slow,Just right,Too much theory
2,3,10/1/2026 6:21:23,Comfortable with libraries like pandas,Student,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Cloud data platforms (AWS / GCP / Azure), Data...","Live coding sessions, Theory and concepts firs...",4,Just right,Just right,Well balanced
3,4,9/30/2026 17:38:50,I can write basic scripts,Career switcher,Move forward – architecture-level design with ...,"pandas / data manipulation, PySpark, Working w...","Batch vs. streaming pipelines, Data lake / war...",An end-to-end project we build together,4,Just right,Just right,Well balanced
4,5,9/30/2026 17:39:29,Comfortable with libraries like pandas,Career switcher,A mix – short basics refreshers alongside arch...,"PySpark, Working with SQL from Python, APIs an...","ETL vs. ELT patterns, Transformation tools (e....","An end-to-end project we build together, Real-...",3,Just right,Too hard,Too much theory
5,6,9/30/2026 18:04:44,Beginner – still learning the syntax,Career switcher,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","ETL vs. ELT patterns, Orchestration (e.g. Airf...","An end-to-end project we build together, Real-...",3,Just right,Too hard,Well balanced
6,7,9/30/2026 18:11:39,I can write basic scripts,Student,A mix – short basics refreshers alongside arch...,"PySpark, Working with SQL from Python, APIs an...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
7,8,9/30/2026 19:25:51,I can write basic scripts,Front End Developer,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
8,9,9/30/2026 19:40:52,I can write basic scripts,Full Stack Web Developer,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
9,10,9/30/2026 19:55:48,I can write basic scripts,Career switcher,Move forward – architecture-level design with ...,"pandas / data manipulation, PySpark, Working w...","Data lake / warehouse / lakehouse design, ETL ...","An end-to-end project we build together, Real-...",5,Just right,Just right,Too much theory
10,11,9/30/2026 20:08:19,Beginner – still learning the syntax,None,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...",I don't have much information about it,"Live coding sessions, An end-to-end project we...",3,Just right,Just right,Well balanced
11,12,9/30/2026 21:37:16,Beginner – still learning the syntax,Data / BI analyst,Strengthen basics – Python and core libraries ...,"Core Python (functions, OOP, error handling)",Batch vs. streaming pipelines,Live coding sessions,1,Just right,Just right,Well balanced
12,13,9/30/2026 21:54:53,I can write basic scripts,Student,Move forward – architecture-level design with ...,"PySpark, APIs and data ingestion (requests, JSON)","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
13,14,9/30/2026 22:33:18,Comfortable with libraries like pandas,Student and switch the career,Move forward – architecture-level design with ...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","Live coding sessions, Real-world case studies,...",3,Just right,Just right,Too much theory
14,15,9/30/2026 22:35:01,I can write basic scripts,Data / BI analyst,Strengthen basics – Python and core libraries ...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","Live coding sessions, Real-world case studies,...",3,Just right,Just right,"Too much hands-on, not enough explanation"
15,16,9/30/2026 23:17:35,Comfortable with libraries like pandas,Data / BI analyst,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, Working w...","ETL vs. ELT patterns, Orchestration (e.g. Airf...","Live coding sessions, Theory and concepts first",4,Just right,Just right,Too much theory
16,17,9/30/2026 23:19:59,Comfortable with libraries like pandas,Data / BI analyst,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, APIs and ...","Batch vs. streaming pipelines, Transformation ...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
17,18,9/30/2026 23:38:10,Beginner – still learning the syntax,Career switcher,A mix – short basics refreshers alongside arch...,Working with SQL from Python,"Data lake / warehouse / lakehouse design, Data...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
18,19,9/30/2026 23:52:23,I can write basic scripts,Student,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","An end-to-end project we build together, Real-...",4,Just right,Too hard,Well balanced

### Cell 2 explanation

This cell imports pandasql, which allows SQL queries to run against pandas DataFrames. It loads the CSV and uses ROW_NUMBER() OVER (ORDER BY response_time) to create a sequential survey_key for every response. The key is assigned after ordering by response time and is used to connect the main survey table with the normalized topic and learning-style tables created later.

The asterisk selects all original columns in addition to the new key. The resulting df has one row per respondent and one new identifier column.

In [3]:
query = """
SELECT
    ROW_NUMBER() OVER (ORDER BY response_time) AS survey_key,
    response_time,
    python_level,
    background,
    class_direction,
    python_topics,
    architecture_topics,
    learning_style,
    expectations_rating,
    pace,
    difficulty,
    theory_practice_balance
FROM df
"""

main_table = sqldf(query, {"df": df})
main_table

,survey_key,response_time,python_level,background,class_direction,python_topics,architecture_topics,learning_style,expectations_rating,pace,difficulty,theory_practice_balance
0,1,10/1/2026 0:35:57,Comfortable with libraries like pandas,Student,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, APIs and ...","Batch vs. streaming pipelines, Data lake / war...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
1,2,10/1/2026 0:40:00,I can write basic scripts,Student,Move forward – architecture-level design with ...,"PySpark, Working with SQL from Python, APIs an...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",3,Too slow,Just right,Too much theory
2,3,10/1/2026 6:21:23,Comfortable with libraries like pandas,Student,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Cloud data platforms (AWS / GCP / Azure), Data...","Live coding sessions, Theory and concepts firs...",4,Just right,Just right,Well balanced
3,4,9/30/2026 17:38:50,I can write basic scripts,Career switcher,Move forward – architecture-level design with ...,"pandas / data manipulation, PySpark, Working w...","Batch vs. streaming pipelines, Data lake / war...",An end-to-end project we build together,4,Just right,Just right,Well balanced
4,5,9/30/2026 17:39:29,Comfortable with libraries like pandas,Career switcher,A mix – short basics refreshers alongside arch...,"PySpark, Working with SQL from Python, APIs an...","ETL vs. ELT patterns, Transformation tools (e....","An end-to-end project we build together, Real-...",3,Just right,Too hard,Too much theory
5,6,9/30/2026 18:04:44,Beginner – still learning the syntax,Career switcher,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","ETL vs. ELT patterns, Orchestration (e.g. Airf...","An end-to-end project we build together, Real-...",3,Just right,Too hard,Well balanced
6,7,9/30/2026 18:11:39,I can write basic scripts,Student,A mix – short basics refreshers alongside arch...,"PySpark, Working with SQL from Python, APIs an...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
7,8,9/30/2026 19:25:51,I can write basic scripts,Front End Developer,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
8,9,9/30/2026 19:40:52,I can write basic scripts,Full Stack Web Developer,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
9,10,9/30/2026 19:55:48,I can write basic scripts,Career switcher,Move forward – architecture-level design with ...,"pandas / data manipulation, PySpark, Working w...","Data lake / warehouse / lakehouse design, ETL ...","An end-to-end project we build together, Real-...",5,Just right,Just right,Too much theory
10,11,9/30/2026 20:08:19,Beginner – still learning the syntax,None,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...",I don't have much information about it,"Live coding sessions, An end-to-end project we...",3,Just right,Just right,Well balanced
11,12,9/30/2026 21:37:16,Beginner – still learning the syntax,Data / BI analyst,Strengthen basics – Python and core libraries ...,"Core Python (functions, OOP, error handling)",Batch vs. streaming pipelines,Live coding sessions,1,Just right,Just right,Well balanced
12,13,9/30/2026 21:54:53,I can write basic scripts,Student,Move forward – architecture-level design with ...,"PySpark, APIs and data ingestion (requests, JSON)","Batch vs. streaming pipelines, Data lake / war...","Live coding sessions, An end-to-end project we...",4,Just right,Just right,Well balanced
13,14,9/30/2026 22:33:18,Comfortable with libraries like pandas,Student and switch the career,Move forward – architecture-level design with ...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","Live coding sessions, Real-world case studies,...",3,Just right,Just right,Too much theory
14,15,9/30/2026 22:35:01,I can write basic scripts,Data / BI analyst,Strengthen basics – Python and core libraries ...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","Live coding sessions, Real-world case studies,...",3,Just right,Just right,"Too much hands-on, not enough explanation"
15,16,9/30/2026 23:17:35,Comfortable with libraries like pandas,Data / BI analyst,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, Working w...","ETL vs. ELT patterns, Orchestration (e.g. Airf...","Live coding sessions, Theory and concepts first",4,Just right,Just right,Too much theory
16,17,9/30/2026 23:19:59,Comfortable with libraries like pandas,Data / BI analyst,A mix – short basics refreshers alongside arch...,"pandas / data manipulation, PySpark, APIs and ...","Batch vs. streaming pipelines, Transformation ...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
17,18,9/30/2026 23:38:10,Beginner – still learning the syntax,Career switcher,A mix – short basics refreshers alongside arch...,Working with SQL from Python,"Data lake / warehouse / lakehouse design, Data...","An end-to-end project we build together, Real-...",4,Just right,Just right,Well balanced
18,19,9/30/2026 23:52:23,I can write basic scripts,Student,A mix – short basics refreshers alongside arch...,"Core Python (functions, OOP, error handling), ...","Data lake / warehouse / lakehouse design, ETL ...","An end-to-end project we build together, Real-...",4,Just right,Too hard,Well balanced

### Cell 4 explanation

This cell creates main_table, the respondent-level table. It explicitly selects the survey key and every required survey field instead of using an asterisk. Explicit column selection documents the output schema and prevents unexpected input columns from being copied into the result.

There is still one row per survey response. The multi-selection fields remain in their original comma-separated form here because this table preserves the complete response.

In [4]:
# Select the respondent key and the multi-select Python topics column.
python_topics = sqldf("SELECT survey_key, python_topics FROM df", {"df": df})

# Convert each comma-separated topic string into a list of topics.
python_topics["python_topics"] = python_topics["python_topics"].str.split(",")

# Display the intermediate list representation.
python_topics

    survey_key                                      python_topics
0            1  [pandas / data manipulation,  PySpark,  APIs a...
1            2  [PySpark,  Working with SQL from Python,  APIs...
2            3  [Core Python (functions,  OOP,  error handling...
3            4  [pandas / data manipulation,  PySpark,  Workin...
4            5  [PySpark,  Working with SQL from Python,  APIs...
5            6  [Core Python (functions,  OOP,  error handling...
6            7  [PySpark,  Working with SQL from Python,  APIs...
7            8  [Core Python (functions,  OOP,  error handling...
8            9  [Core Python (functions,  OOP,  error handling...
9           10  [pandas / data manipulation,  PySpark,  Workin...
10          11  [Core Python (functions,  OOP,  error handling...
11          12   [Core Python (functions,  OOP,  error handling)]
12          13  [PySpark,  APIs and data ingestion (requests, ...
13          14  [Core Python (functions,  OOP,  error handling...
14          15  [Core Python (functions,  OOP,  error handling...
15          16  [pandas / data manipulation,  PySpark,  Workin...
16          17  [pandas / data manipulation,  PySpark,  APIs a...
17          18                     [Working with SQL from Python]
18          19  [Core Python (functions,  OOP,  error handling...

### Cell 5 explanation

This cell extracts only survey_key and python_topics. A respondent can select several Python topics, so the values are stored together in one comma-separated string.

str.split(",") changes each string into a Python list. This is an intermediate step: each respondent is still represented by one DataFrame row, but the topic column now contains a list of selected topics.

In [5]:
# Select and split the Python topics before normalizing them into rows.
python_topics = sqldf("SELECT survey_key, python_topics FROM df", {"df": df})
python_topics["python_topics"] = python_topics["python_topics"].str.split(",")

# Create one row per selected Python topic and reset the DataFrame index.
python_topics = python_topics.explode("python_topics", ignore_index=True)
python_topics

    survey_key                       python_topics
0            1          pandas / data manipulation
1            1                             PySpark
2            1   APIs and data ingestion (requests
3            1                               JSON)
4            2                             PySpark
..         ...                                 ...
89          19                             PySpark
90          19        Working with SQL from Python
91          19   APIs and data ingestion (requests
92          19                               JSON)
93          19            Testing and code quality

[94 rows x 2 columns]

### Cell 6 explanation

This cell repeats the Python-topic extraction and then uses explode("python_topics") to create one row for every selected topic. The respondent key is repeated on each new row, preserving the relationship between the respondent and each topic.

ignore_index=True creates a fresh sequential pandas index. The output contains 94 topic selections in two columns: survey_key and python_topics. This normalized structure makes counting and filtering topics much easier.

In [6]:
# Select the respondent key and the multi-select architecture topics column.
architecture_topics = sqldf("SELECT survey_key, architecture_topics FROM df", {"df": df})
architecture_topics["architecture_topics"] = architecture_topics["architecture_topics"].str.split(",")

# Create one row per selected architecture topic.
architecture_topics = architecture_topics.explode("architecture_topics", ignore_index=True)
architecture_topics

     survey_key                        architecture_topics
0             1              Batch vs. streaming pipelines
1             1   Data lake / warehouse / lakehouse design
2             1                       ETL vs. ELT patterns
3             1               Orchestration (e.g. Airflow)
4             1            Transformation tools (e.g. dbt)
..          ...                                        ...
109          18                 Data modeling (star schema
110          18                                      SCDs)
111          19   Data lake / warehouse / lakehouse design
112          19                       ETL vs. ELT patterns
113          19            Transformation tools (e.g. dbt)

[114 rows x 2 columns]

### Cell 7 explanation

This cell applies the same normalization pattern to architecture_topics. It selects the respondent key and architecture-topic column, splits the comma-separated values into lists, and explodes those lists into separate rows.

The output contains 114 individual architecture-topic selections. Each row represents one respondent-topic relationship, and survey_key identifies the respondent who selected it.

In [7]:
# Select and split the respondent learning-style selections.
learning_style = sqldf("SELECT survey_key, learning_style FROM df", {"df": df})
learning_style["learning_style"] = learning_style["learning_style"].str.split(",")

# Create one row per selected learning style.
learning_style = learning_style.explode("learning_style", ignore_index=True)
learning_style

    survey_key                            learning_style
0            1   An end-to-end project we build together
1            1                   Real-world case studies
2            1                 Theory and concepts first
3            1             Homework / practice exercises
4            2                      Live coding sessions
5            2   An end-to-end project we build together
6            2                   Real-world case studies
7            2             Homework / practice exercises
8            3                      Live coding sessions
9            3                 Theory and concepts first
10           3             Homework / practice exercises
11           4   An end-to-end project we build together
12           5   An end-to-end project we build together
13           5                   Real-world case studies
14           6   An end-to-end project we build together
15           6                   Real-world case studies
16           6             Homework / practice exercises
17           7                      Live coding sessions
18           7   An end-to-end project we build together
19           7                   Real-world case studies
20           7             Homework / practice exercises
21           8                      Live coding sessions
22           8   An end-to-end project we build together
23           8                   Real-world case studies
24           8                 Theory and concepts first
25           8             Homework / practice exercises
26           9                      Live coding sessions
27           9   An end-to-end project we build together
28           9                   Real-world case studies
29           9                 Theory and concepts first
30           9             Homework / practice exercises
31          10   An end-to-end project we build together
32          10                   Real-world case studies
33          11                      Live coding sessions
34          11   An end-to-end project we build together
35          11                   Real-world case studies
36          11                 Theory and concepts first
37          11             Homework / practice exercises
38          12                      Live coding sessions
39          13                      Live coding sessions
40          13   An end-to-end project we build together
41          13                   Real-world case studies
42          13                 Theory and concepts first
43          14                      Live coding sessions
44          14                   Real-world case studies
45          14             Homework / practice exercises
46          15                      Live coding sessions
47          15                   Real-world case studies
48          15             Homework / practice exercises
49          16                      Live coding sessions
50          16                 Theory and concepts first
51          17   An end-to-end project we build together
52          17                   Real-world case studies
53          18   An end-to-end project we build together
54          18                   Real-world case studies
55          18                 Theory and concepts first
56          19   An end-to-end project we build together
57          19                   Real-world case studies
58          19                 Theory and concepts first
59          19             Homework / practice exercises

### Cell 8 explanation

This cell normalizes the learning_style column. Multiple learning styles are split at commas and then expanded into separate rows. The respondent key is repeated for every selected style.

The output contains 59 individual learning-style selections. This format allows the data to be grouped, counted, filtered, or joined to the main survey table.

In [8]:
# Save the respondent-level table.
main_table.to_parquet(r"F:\Big Data\Survey\target\main_table.parquet", engine="fastparquet", index=False)

# Save each normalized multi-select table.
learning_style.to_parquet(r"F:\Big Data\Survey\target\learning_style.parquet", engine="fastparquet", index=False)
architecture_topics.to_parquet(r"F:\Big Data\Survey\target\architecture_topics.parquet", engine="fastparquet", index=False)
python_topics.to_parquet(r"F:\Big Data\Survey\target\python_topics.parquet", engine="fastparquet", index=False)

### Cell 9 explanation

This cell loads the four transformed DataFrames into the target folder as Parquet files. Parquet is a column-oriented format that is usually smaller and faster for analytical workloads than CSV, while also preserving data types.

main_table.parquet stores one complete row per survey response. python_topics.parquet, architecture_topics.parquet, and learning_style.parquet store one normalized selection per row.

engine="fastparquet" selects the Parquet writer, and index=False prevents pandas internal row numbers from being saved as an unwanted extra column.

### Cell 10 explanation

This empty code cell is a placeholder for future analysis. It currently performs no operation and does not change any data.